/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frmQLTV;

import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Phieunhapsach;

/**
 *
 * @author My PC
 */
public class frmPHIEUNHAP extends javax.swing.JFrame {

    /**
     * Creates new form frmMENU
     */
    List<Phieunhapsach> list = new ArrayList<>();

    public frmPHIEUNHAP() {
        initComponents();
        this.setSize(800, 550);
        lblBR.setIcon(new ImageIcon(getClass().getResource("/BR/brpn-1.jpg")));
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btnDANGXUAT = new javax.swing.JButton();
        btnSACH = new javax.swing.JButton();
        btnPHIEUNHAP = new javax.swing.JButton();
        btnPHIEUMUON = new javax.swing.JButton();
        btnPHIEUMUONCT = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        PHIEUNHAPSACH = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPHIEUNHAP = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtMAPN = new javax.swing.JTextField();
        txtPNMASACH = new javax.swing.JTextField();
        txtPNMANV = new javax.swing.JTextField();
        txtPNSOLUONG = new javax.swing.JTextField();
        txtPNNGAYNHAP = new javax.swing.JTextField();
        txtPNGIA = new javax.swing.JTextField();
        btnPNNHAPMOI = new javax.swing.JButton();
        btnPNTHEMMOI = new javax.swing.JButton();
        btnPNCAPNHAT = new javax.swing.JButton();
        btnPNXOA = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        ckbMAPN = new javax.swing.JCheckBox();
        ckbPNMASACH = new javax.swing.JCheckBox();
        ckbPNNGAYNHAP = new javax.swing.JCheckBox();
        btnPNSEACH = new javax.swing.JButton();
        lblBR = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mitDANGXUAT = new javax.swing.JMenuItem();
        mitDOIMK = new javax.swing.JMenuItem();
        mitTHOAT = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mitNHANVIEN = new javax.swing.JMenuItem();
        mitDOCGIA = new javax.swing.JMenuItem();
        mitSACH = new javax.swing.JMenuItem();
        mitTACGIA = new javax.swing.JMenuItem();
        mitNXB = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mitPHIEUNHAP = new javax.swing.JMenuItem();
        mitPHIEUMUON = new javax.swing.JMenuItem();
        mitPHIEUMUONCT = new javax.swing.JMenuItem();
        mitTHONGKE = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mitHDSD = new javax.swing.JMenuItem();
        mitTTPB = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÝ THƯ VIỆN");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setRollover(true);
        jToolBar1.setToolTipText("");

        btnDANGXUAT.setBackground(new java.awt.Color(255, 255, 255));
        btnDANGXUAT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnDANGXUAT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/icondx1.jpg"))); // NOI18N
        btnDANGXUAT.setText("Đăng xuất");
        btnDANGXUAT.setFocusable(false);
        btnDANGXUAT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDANGXUAT.setMaximumSize(new java.awt.Dimension(91, 51));
        btnDANGXUAT.setMinimumSize(new java.awt.Dimension(91, 51));
        btnDANGXUAT.setPreferredSize(new java.awt.Dimension(91, 51));
        btnDANGXUAT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDANGXUAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDANGXUATActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDANGXUAT);

        btnSACH.setBackground(new java.awt.Color(255, 255, 255));
        btnSACH.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSACH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconbook1.jpg"))); // NOI18N
        btnSACH.setText("Sách");
        btnSACH.setFocusable(false);
        btnSACH.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSACH.setMaximumSize(new java.awt.Dimension(91, 51));
        btnSACH.setMinimumSize(new java.awt.Dimension(91, 51));
        btnSACH.setPreferredSize(new java.awt.Dimension(91, 51));
        btnSACH.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSACH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSACHActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSACH);

        btnPHIEUNHAP.setBackground(new java.awt.Color(255, 255, 255));
        btnPHIEUNHAP.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnPHIEUNHAP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconphieunhapsach1.jpg"))); // NOI18N
        btnPHIEUNHAP.setText("Phiếu nhập");
        btnPHIEUNHAP.setFocusable(false);
        btnPHIEUNHAP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPHIEUNHAP.setMaximumSize(new java.awt.Dimension(91, 51));
        btnPHIEUNHAP.setMinimumSize(new java.awt.Dimension(91, 51));
        btnPHIEUNHAP.setPreferredSize(new java.awt.Dimension(91, 51));
        btnPHIEUNHAP.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPHIEUNHAP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPHIEUNHAPActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPHIEUNHAP);

        btnPHIEUMUON.setBackground(new java.awt.Color(255, 255, 255));
        btnPHIEUMUON.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnPHIEUMUON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconphieumuon1.jpg"))); // NOI18N
        btnPHIEUMUON.setText("Phiếu mượn");
        btnPHIEUMUON.setFocusable(false);
        btnPHIEUMUON.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPHIEUMUON.setMaximumSize(new java.awt.Dimension(91, 51));
        btnPHIEUMUON.setMinimumSize(new java.awt.Dimension(91, 51));
        btnPHIEUMUON.setPreferredSize(new java.awt.Dimension(91, 51));
        btnPHIEUMUON.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPHIEUMUON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPHIEUMUONActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPHIEUMUON);

        btnPHIEUMUONCT.setBackground(new java.awt.Color(255, 255, 255));
        btnPHIEUMUONCT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnPHIEUMUONCT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconphieumuonct1.jpg"))); // NOI18N
        btnPHIEUMUONCT.setText("Phiếu mượn CT");
        btnPHIEUMUONCT.setFocusable(false);
        btnPHIEUMUONCT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPHIEUMUONCT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPHIEUMUONCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPHIEUMUONCTActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPHIEUMUONCT);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        PHIEUNHAPSACH.setBackground(new java.awt.Color(255, 255, 255));
        PHIEUNHAPSACH.setToolTipText("");
        PHIEUNHAPSACH.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PHIEUNHAPSACH.setOpaque(false);

        tblPHIEUNHAP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã phiếu nhập", "Mã sách", "Số lượng", "Ngày nhập", "Giá", "Mã nhân viên"
            }
        ));
        jScrollPane2.setViewportView(tblPHIEUNHAP);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 255));
        jLabel9.setText("Mã phiếu nhập");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 255));
        jLabel10.setText("Mã sách");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 255));
        jLabel11.setText("Mã nhân viên ");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 255));
        jLabel12.setText("Số lượng");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 255));
        jLabel13.setText("Ngày nhập");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 255));
        jLabel14.setText("Giá");

        btnPNNHAPMOI.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPNNHAPMOI.setForeground(new java.awt.Color(51, 51, 51));
        btnPNNHAPMOI.setText("Nhập mới");
        btnPNNHAPMOI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPNNHAPMOIActionPerformed(evt);
            }
        });

        btnPNTHEMMOI.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPNTHEMMOI.setForeground(new java.awt.Color(51, 51, 51));
        btnPNTHEMMOI.setText("Thêm mới");
        btnPNTHEMMOI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPNTHEMMOIActionPerformed(evt);
            }
        });

        btnPNCAPNHAT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPNCAPNHAT.setForeground(new java.awt.Color(51, 51, 51));
        btnPNCAPNHAT.setText("Cập nhật");
        btnPNCAPNHAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPNCAPNHATActionPerformed(evt);
            }
        });

        btnPNXOA.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPNXOA.setForeground(new java.awt.Color(51, 51, 51));
        btnPNXOA.setText("Xóa");
        btnPNXOA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPNXOAActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm kiếm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jPanel4.setOpaque(false);

        buttonGroup2.add(ckbMAPN);
        ckbMAPN.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ckbMAPN.setForeground(new java.awt.Color(0, 0, 255));
        ckbMAPN.setText("Mã phiếu nhập");

        buttonGroup2.add(ckbPNMASACH);
        ckbPNMASACH.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ckbPNMASACH.setForeground(new java.awt.Color(0, 0, 255));
        ckbPNMASACH.setText("Mã sách");

        buttonGroup2.add(ckbPNNGAYNHAP);
        ckbPNNGAYNHAP.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ckbPNNGAYNHAP.setForeground(new java.awt.Color(0, 0, 255));
        ckbPNNGAYNHAP.setText("Ngày nhập");

        btnPNSEACH.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPNSEACH.setForeground(new java.awt.Color(51, 51, 51));
        btnPNSEACH.setText("SEACH");
        btnPNSEACH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPNSEACHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ckbPNNGAYNHAP)
                    .addComponent(ckbPNMASACH)
                    .addComponent(ckbMAPN)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnPNSEACH)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(ckbMAPN)
                .addGap(18, 18, 18)
                .addComponent(ckbPNMASACH)
                .addGap(18, 18, 18)
                .addComponent(ckbPNNGAYNHAP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btnPNSEACH))
        );

        javax.swing.GroupLayout PHIEUNHAPSACHLayout = new javax.swing.GroupLayout(PHIEUNHAPSACH);
        PHIEUNHAPSACH.setLayout(PHIEUNHAPSACHLayout);
        PHIEUNHAPSACHLayout.setHorizontalGroup(
            PHIEUNHAPSACHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PHIEUNHAPSACHLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(PHIEUNHAPSACHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PHIEUNHAPSACHLayout.createSequentialGroup()
                        .addGroup(PHIEUNHAPSACHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PHIEUNHAPSACHLayout.createSequentialGroup()
                                .addGroup(PHIEUNHAPSACHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PHIEUNHAPSACHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PHIEUNHAPSACHLayout.createSequentialGroup()
                                            .addComponent(jLabel9)
                                            .addGap(38, 38, 38))
                                        .addGroup(PHIEUNHAPSACHLayout.createSequentialGroup()
                                            .addComponent(jLabel10)
                                            .addGap(78, 78, 78)))
                                    .addGroup(PHIEUNHAPSACHLayout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(42, 42, 42)))
                                .addGroup(PHIEUNHAPSACHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMAPN)
                                    .addComponent(txtPNMASACH)
                                    .addComponent(txtPNMANV, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
                                .addGap(36, 36, 36)
                                .addGroup(PHIEUNHAPSACHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PHIEUNHAPSACHLayout.createSequentialGroup()
                                        .addGroup(PHIEUNHAPSACHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel14))
                                        .addGap(28, 28, 28)
                                        .addGroup(PHIEUNHAPSACHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtPNNGAYNHAP, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtPNGIA, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(PHIEUNHAPSACHLayout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(40, 40, 40)
                                        .addComponent(txtPNSOLUONG, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(53, 53, 53))
                            .addGroup(PHIEUNHAPSACHLayout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(btnPNNHAPMOI)
                                .addGap(49, 49, 49)
                                .addComponent(btnPNTHEMMOI)
                                .addGap(48, 48, 48)
                                .addComponent(btnPNCAPNHAT)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                                .addComponent(btnPNXOA, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)))
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(696, 696, 696))
        );
        PHIEUNHAPSACHLayout.setVerticalGroup(
            PHIEUNHAPSACHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PHIEUNHAPSACHLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PHIEUNHAPSACHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PHIEUNHAPSACHLayout.createSequentialGroup()
                        .addGroup(PHIEUNHAPSACHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel12)
                            .addComponent(txtMAPN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPNSOLUONG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(PHIEUNHAPSACHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel13)
                            .addComponent(txtPNMASACH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPNNGAYNHAP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(PHIEUNHAPSACHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel14)
                            .addComponent(txtPNMANV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPNGIA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PHIEUNHAPSACHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPNNHAPMOI)
                            .addComponent(btnPNTHEMMOI)
                            .addComponent(btnPNCAPNHAT)
                            .addComponent(btnPNXOA)))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
        );

        lblBR.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBR.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblBR.setName(""); // NOI18N
        lblBR.setOpaque(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PHIEUNHAPSACH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblBR, javax.swing.GroupLayout.PREFERRED_SIZE, 1460, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PHIEUNHAPSACH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblBR, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(1046, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenu1.setBackground(new java.awt.Color(255, 255, 255));
        jMenu1.setText("Hệ thống");

        mitDANGXUAT.setBackground(new java.awt.Color(255, 255, 255));
        mitDANGXUAT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/icondx1.jpg"))); // NOI18N
        mitDANGXUAT.setText("Đăng xuất");
        mitDANGXUAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitDANGXUATActionPerformed(evt);
            }
        });
        jMenu1.add(mitDANGXUAT);

        mitDOIMK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/icondmk.jpg"))); // NOI18N
        mitDOIMK.setText("Đổi mật khẩu");
        mitDOIMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitDOIMKActionPerformed(evt);
            }
        });
        jMenu1.add(mitDOIMK);

        mitTHOAT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconexit1.jpg"))); // NOI18N
        mitTHOAT.setText("Thoát");
        mitTHOAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitTHOATActionPerformed(evt);
            }
        });
        jMenu1.add(mitTHOAT);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Quản lý");

        mitNHANVIEN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconnv1.jpg"))); // NOI18N
        mitNHANVIEN.setText("Nhân viên");
        mitNHANVIEN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitNHANVIENActionPerformed(evt);
            }
        });
        jMenu2.add(mitNHANVIEN);

        mitDOCGIA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/icondocgia1.jpg"))); // NOI18N
        mitDOCGIA.setText("Độc giả");
        mitDOCGIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitDOCGIAActionPerformed(evt);
            }
        });
        jMenu2.add(mitDOCGIA);

        mitSACH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconbook1.jpg"))); // NOI18N
        mitSACH.setText("Sách");
        mitSACH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitSACHActionPerformed(evt);
            }
        });
        jMenu2.add(mitSACH);

        mitTACGIA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/icontacgia1.jpg"))); // NOI18N
        mitTACGIA.setText("Tác giả");
        mitTACGIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitTACGIAActionPerformed(evt);
            }
        });
        jMenu2.add(mitTACGIA);

        mitNXB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconnxb1.jpg"))); // NOI18N
        mitNXB.setText("Nhà xuất bản");
        mitNXB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitNXBActionPerformed(evt);
            }
        });
        jMenu2.add(mitNXB);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Thống kê");

        mitPHIEUNHAP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconphieunhapsach1.jpg"))); // NOI18N
        mitPHIEUNHAP.setText("Phiếu nhập sách");
        mitPHIEUNHAP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitPHIEUNHAPActionPerformed(evt);
            }
        });
        jMenu3.add(mitPHIEUNHAP);

        mitPHIEUMUON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconphieumuon1.jpg"))); // NOI18N
        mitPHIEUMUON.setText("Phiếu mượn sách");
        mitPHIEUMUON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitPHIEUMUONActionPerformed(evt);
            }
        });
        jMenu3.add(mitPHIEUMUON);

        mitPHIEUMUONCT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconphieumuonct1.jpg"))); // NOI18N
        mitPHIEUMUONCT.setText("Phiếu mượn sách chi tiết");
        mitPHIEUMUONCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitPHIEUMUONCTActionPerformed(evt);
            }
        });
        jMenu3.add(mitPHIEUMUONCT);

        mitTHONGKE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconbdtk.jpg"))); // NOI18N
        mitTHONGKE.setText("Thống kê số liệu");
        mitTHONGKE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitTHONGKEActionPerformed(evt);
            }
        });
        jMenu3.add(mitTHONGKE);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Trợ giúp");

        mitHDSD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconhdsd1.jpg"))); // NOI18N
        mitHDSD.setText("Hướng dẫn sử dụng");
        jMenu4.add(mitHDSD);

        mitTTPB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/gt_1.png"))); // NOI18N
        mitTTPB.setText("Thông tin phiên bản");
        jMenu4.add(mitTTPB);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mitDANGXUATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitDANGXUATActionPerformed
        frmDANGNHAP frmDN;
        try {
            frmDN = new frmDANGNHAP();;
            frmDN.show();
            dispose();
        } catch (ClassNotFoundException | SQLException ex1) {
            Logger.getLogger(frmDANGNHAP.class.getName()).log(Level.SEVERE, null, ex1);
        }
    }//GEN-LAST:event_mitDANGXUATActionPerformed

    private void mitTHOATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitTHOATActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mitTHOATActionPerformed

    private void btnSACHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSACHActionPerformed
        frmSACH frmS = new frmSACH();
        frmS.show();
        dispose();
    }//GEN-LAST:event_btnSACHActionPerformed

    private void btnPHIEUNHAPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPHIEUNHAPActionPerformed
        frmPHIEUNHAP frmPN;
        frmPN = new frmPHIEUNHAP();
        frmPN.show();
        dispose();
    }//GEN-LAST:event_btnPHIEUNHAPActionPerformed

    private void btnPHIEUMUONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPHIEUMUONActionPerformed
        frmPHIEUMUON frmPM = new frmPHIEUMUON();
        frmPM.show();
        dispose();
    }//GEN-LAST:event_btnPHIEUMUONActionPerformed

    private void btnPHIEUMUONCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPHIEUMUONCTActionPerformed
        frmPHIEUMUONCT frmPMCT = new frmPHIEUMUONCT();
        frmPMCT.show();
        dispose();
    }//GEN-LAST:event_btnPHIEUMUONCTActionPerformed

    private void mitNHANVIENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitNHANVIENActionPerformed
        frmNNHANVIEN frmNV = new frmNNHANVIEN();
        frmNV.show();
        dispose();
    }//GEN-LAST:event_mitNHANVIENActionPerformed

    private void mitDOCGIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitDOCGIAActionPerformed
        frmDOCGIA frmDG = new frmDOCGIA();
        frmDG.show();
        dispose();
    }//GEN-LAST:event_mitDOCGIAActionPerformed

    private void mitSACHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitSACHActionPerformed
        frmSACH frmS = new frmSACH();
        frmS.show();
        dispose();
    }//GEN-LAST:event_mitSACHActionPerformed

    private void mitTACGIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitTACGIAActionPerformed
        frmTACGIA frmTG = new frmTACGIA();
        frmTG.show();
        dispose();
    }//GEN-LAST:event_mitTACGIAActionPerformed

    private void mitNXBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitNXBActionPerformed
        frmNXB frmN = new frmNXB();
        frmN.show();
        dispose();
    }//GEN-LAST:event_mitNXBActionPerformed

    private void mitPHIEUNHAPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitPHIEUNHAPActionPerformed
        frmPHIEUNHAP frmPN;
        frmPN = new frmPHIEUNHAP();
        frmPN.show();
        dispose();
    }//GEN-LAST:event_mitPHIEUNHAPActionPerformed

    private void mitPHIEUMUONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitPHIEUMUONActionPerformed
        frmPHIEUMUON frmPM = new frmPHIEUMUON();
        frmPM.show();
        dispose();
    }//GEN-LAST:event_mitPHIEUMUONActionPerformed

    private void mitPHIEUMUONCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitPHIEUMUONCTActionPerformed
        frmPHIEUMUONCT frmPMCT = new frmPHIEUMUONCT();
        frmPMCT.show();
        dispose();
    }//GEN-LAST:event_mitPHIEUMUONCTActionPerformed

    private void mitTHONGKEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitTHONGKEActionPerformed
        frmTHONGKE frmTK = new frmTHONGKE();
        frmTK.show();
        dispose();
    }//GEN-LAST:event_mitTHONGKEActionPerformed

    private void btnPNCAPNHATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPNCAPNHATActionPerformed

    }//GEN-LAST:event_btnPNCAPNHATActionPerformed

    private void btnPNNHAPMOIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPNNHAPMOIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPNNHAPMOIActionPerformed

    private void btnPNTHEMMOIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPNTHEMMOIActionPerformed

    }//GEN-LAST:event_btnPNTHEMMOIActionPerformed

    private void btnPNXOAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPNXOAActionPerformed

    }//GEN-LAST:event_btnPNXOAActionPerformed

    private void btnPNSEACHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPNSEACHActionPerformed

    }//GEN-LAST:event_btnPNSEACHActionPerformed

    private void btnDANGXUATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDANGXUATActionPerformed
        frmDANGNHAP frmDN;
        try {
            frmDN = new frmDANGNHAP();;
            frmDN.show();
            dispose();
        } catch (ClassNotFoundException | SQLException ex1) {
            Logger.getLogger(frmDANGNHAP.class.getName()).log(Level.SEVERE, null, ex1);
        }
    }//GEN-LAST:event_btnDANGXUATActionPerformed

    private void mitDOIMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitDOIMKActionPerformed
        frmDOIMATKHAU frmDMK;
        try {
            frmDMK = new frmDOIMATKHAU();
            frmDMK.show();
            dispose();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(frmDANGNHAP.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mitDOIMKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPHIEUNHAP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPHIEUNHAP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPHIEUNHAP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPHIEUNHAP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPHIEUNHAP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PHIEUNHAPSACH;
    private javax.swing.JButton btnDANGXUAT;
    private javax.swing.JButton btnPHIEUMUON;
    private javax.swing.JButton btnPHIEUMUONCT;
    private javax.swing.JButton btnPHIEUNHAP;
    private javax.swing.JButton btnPNCAPNHAT;
    private javax.swing.JButton btnPNNHAPMOI;
    private javax.swing.JButton btnPNSEACH;
    private javax.swing.JButton btnPNTHEMMOI;
    private javax.swing.JButton btnPNXOA;
    private javax.swing.JButton btnSACH;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JCheckBox ckbMAPN;
    private javax.swing.JCheckBox ckbPNMASACH;
    private javax.swing.JCheckBox ckbPNNGAYNHAP;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblBR;
    private javax.swing.JMenuItem mitDANGXUAT;
    private javax.swing.JMenuItem mitDOCGIA;
    private javax.swing.JMenuItem mitDOIMK;
    private javax.swing.JMenuItem mitHDSD;
    private javax.swing.JMenuItem mitNHANVIEN;
    private javax.swing.JMenuItem mitNXB;
    private javax.swing.JMenuItem mitPHIEUMUON;
    private javax.swing.JMenuItem mitPHIEUMUONCT;
    private javax.swing.JMenuItem mitPHIEUNHAP;
    private javax.swing.JMenuItem mitSACH;
    private javax.swing.JMenuItem mitTACGIA;
    private javax.swing.JMenuItem mitTHOAT;
    private javax.swing.JMenuItem mitTHONGKE;
    private javax.swing.JMenuItem mitTTPB;
    private javax.swing.JTable tblPHIEUNHAP;
    private javax.swing.JTextField txtMAPN;
    private javax.swing.JTextField txtPNGIA;
    private javax.swing.JTextField txtPNMANV;
    private javax.swing.JTextField txtPNMASACH;
    private javax.swing.JTextField txtPNNGAYNHAP;
    private javax.swing.JTextField txtPNSOLUONG;
    // End of variables declaration//GEN-END:variables

}
