/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frmQLTV;

import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.PhieumuonCT;

/**
 *
 * @author My PC
 */
public class frmPHIEUMUONCT extends javax.swing.JFrame {

    /**
     * Creates new form frmMENU
     */
    List<PhieumuonCT> list = new ArrayList<>();
    private int currentindex;

    public frmPHIEUMUONCT() {
        initComponents();
        this.setSize(570, 540);
        lblBR.setIcon(new ImageIcon(getClass().getResource("/BR/brpmct-1.jpg")));
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btnDANGXUAT = new javax.swing.JButton();
        btnSACH = new javax.swing.JButton();
        btnPHIEUNHAP = new javax.swing.JButton();
        btnPHIEUMUON = new javax.swing.JButton();
        btnPHIEUMUONCT = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        PHIEUMUONCT = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        txtMAPMCT = new javax.swing.JTextField();
        txtPMCTMAPHIEUMUON = new javax.swing.JTextField();
        txtPMCTMASACH = new javax.swing.JTextField();
        jScrollPane8 = new javax.swing.JScrollPane();
        tblPHIEUMUONCHITIET = new javax.swing.JTable();
        btnPMCTNHAPMOI = new javax.swing.JButton();
        btnPMCTTHEMMOI = new javax.swing.JButton();
        btnPMCTCAPNHAT = new javax.swing.JButton();
        btnPMCTXOA = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        ckbMAPMCT = new javax.swing.JCheckBox();
        ckbPMCTMAPHIEUMUON = new javax.swing.JCheckBox();
        ckbPMCTMASACH = new javax.swing.JCheckBox();
        btnPMCTSEACH = new javax.swing.JButton();
        lblBR = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mitDANGXUAT = new javax.swing.JMenuItem();
        mitDOIMK = new javax.swing.JMenuItem();
        mitTHOAT = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mitNHANVIEN = new javax.swing.JMenuItem();
        mitDOCGIA = new javax.swing.JMenuItem();
        mitSACH = new javax.swing.JMenuItem();
        mitTACGIA = new javax.swing.JMenuItem();
        mitNXB = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mitPHIEUNHAP = new javax.swing.JMenuItem();
        mitPHIEUMUON = new javax.swing.JMenuItem();
        mitPHIEUMUONCT = new javax.swing.JMenuItem();
        mitTHONGKE = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mitHDSD = new javax.swing.JMenuItem();
        mitTTPB = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÝ THƯ VIỆN");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setRollover(true);
        jToolBar1.setToolTipText("");

        btnDANGXUAT.setBackground(new java.awt.Color(255, 255, 255));
        btnDANGXUAT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnDANGXUAT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/icondx1.jpg"))); // NOI18N
        btnDANGXUAT.setText("Đăng xuất");
        btnDANGXUAT.setFocusable(false);
        btnDANGXUAT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDANGXUAT.setMaximumSize(new java.awt.Dimension(91, 51));
        btnDANGXUAT.setMinimumSize(new java.awt.Dimension(91, 51));
        btnDANGXUAT.setPreferredSize(new java.awt.Dimension(91, 51));
        btnDANGXUAT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDANGXUAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDANGXUATActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDANGXUAT);

        btnSACH.setBackground(new java.awt.Color(255, 255, 255));
        btnSACH.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSACH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconbook1.jpg"))); // NOI18N
        btnSACH.setText("Sách");
        btnSACH.setFocusable(false);
        btnSACH.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSACH.setMaximumSize(new java.awt.Dimension(91, 51));
        btnSACH.setMinimumSize(new java.awt.Dimension(91, 51));
        btnSACH.setPreferredSize(new java.awt.Dimension(91, 51));
        btnSACH.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSACH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSACHActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSACH);

        btnPHIEUNHAP.setBackground(new java.awt.Color(255, 255, 255));
        btnPHIEUNHAP.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnPHIEUNHAP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconphieunhapsach1.jpg"))); // NOI18N
        btnPHIEUNHAP.setText("Phiếu nhập");
        btnPHIEUNHAP.setFocusable(false);
        btnPHIEUNHAP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPHIEUNHAP.setMaximumSize(new java.awt.Dimension(91, 51));
        btnPHIEUNHAP.setMinimumSize(new java.awt.Dimension(91, 51));
        btnPHIEUNHAP.setPreferredSize(new java.awt.Dimension(91, 51));
        btnPHIEUNHAP.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPHIEUNHAP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPHIEUNHAPActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPHIEUNHAP);

        btnPHIEUMUON.setBackground(new java.awt.Color(255, 255, 255));
        btnPHIEUMUON.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnPHIEUMUON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconphieumuon1.jpg"))); // NOI18N
        btnPHIEUMUON.setText("Phiếu mượn");
        btnPHIEUMUON.setFocusable(false);
        btnPHIEUMUON.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPHIEUMUON.setMaximumSize(new java.awt.Dimension(91, 51));
        btnPHIEUMUON.setMinimumSize(new java.awt.Dimension(91, 51));
        btnPHIEUMUON.setPreferredSize(new java.awt.Dimension(91, 51));
        btnPHIEUMUON.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPHIEUMUON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPHIEUMUONActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPHIEUMUON);

        btnPHIEUMUONCT.setBackground(new java.awt.Color(255, 255, 255));
        btnPHIEUMUONCT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnPHIEUMUONCT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconphieumuonct1.jpg"))); // NOI18N
        btnPHIEUMUONCT.setText("Phiếu mượn CT");
        btnPHIEUMUONCT.setFocusable(false);
        btnPHIEUMUONCT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPHIEUMUONCT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPHIEUMUONCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPHIEUMUONCTActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPHIEUMUONCT);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        PHIEUMUONCT.setBackground(new java.awt.Color(255, 255, 255));
        PHIEUMUONCT.setOpaque(false);

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(0, 0, 255));
        jLabel38.setText("Mã phiếu mượn chi tiết");

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(0, 0, 255));
        jLabel39.setText("Mã sách");

        jLabel40.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(0, 0, 255));
        jLabel40.setText("Mã phiếu mượn");

        tblPHIEUMUONCHITIET.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã phiếu mượn chi tiết", "Mã phiếu mượn", "Mã sách"
            }
        ));
        jScrollPane8.setViewportView(tblPHIEUMUONCHITIET);

        btnPMCTNHAPMOI.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPMCTNHAPMOI.setForeground(new java.awt.Color(51, 51, 51));
        btnPMCTNHAPMOI.setText("Nhập mới");

        btnPMCTTHEMMOI.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPMCTTHEMMOI.setForeground(new java.awt.Color(51, 51, 51));
        btnPMCTTHEMMOI.setText("Thêm mới");
        btnPMCTTHEMMOI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPMCTTHEMMOIActionPerformed(evt);
            }
        });

        btnPMCTCAPNHAT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPMCTCAPNHAT.setForeground(new java.awt.Color(51, 51, 51));
        btnPMCTCAPNHAT.setText("Cập nhật");
        btnPMCTCAPNHAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPMCTCAPNHATActionPerformed(evt);
            }
        });

        btnPMCTXOA.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPMCTXOA.setForeground(new java.awt.Color(51, 51, 51));
        btnPMCTXOA.setText("Xóa");
        btnPMCTXOA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPMCTXOAActionPerformed(evt);
            }
        });

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm kiếm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jPanel11.setOpaque(false);

        buttonGroup8.add(ckbMAPMCT);
        ckbMAPMCT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ckbMAPMCT.setForeground(new java.awt.Color(0, 0, 255));
        ckbMAPMCT.setText("Mã phiếu mượn CT");

        buttonGroup8.add(ckbPMCTMAPHIEUMUON);
        ckbPMCTMAPHIEUMUON.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ckbPMCTMAPHIEUMUON.setForeground(new java.awt.Color(0, 0, 255));
        ckbPMCTMAPHIEUMUON.setText("Mã phiếu mượn");

        buttonGroup8.add(ckbPMCTMASACH);
        ckbPMCTMASACH.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ckbPMCTMASACH.setForeground(new java.awt.Color(0, 0, 255));
        ckbPMCTMASACH.setText("Mã sách");

        btnPMCTSEACH.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPMCTSEACH.setForeground(new java.awt.Color(51, 51, 51));
        btnPMCTSEACH.setText("SEACH");
        btnPMCTSEACH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPMCTSEACHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ckbMAPMCT)
                    .addComponent(ckbPMCTMASACH)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnPMCTSEACH)
                        .addComponent(ckbPMCTMAPHIEUMUON)))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(ckbMAPMCT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ckbPMCTMAPHIEUMUON)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ckbPMCTMASACH)
                .addGap(18, 18, 18)
                .addComponent(btnPMCTSEACH)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PHIEUMUONCTLayout = new javax.swing.GroupLayout(PHIEUMUONCT);
        PHIEUMUONCT.setLayout(PHIEUMUONCTLayout);
        PHIEUMUONCTLayout.setHorizontalGroup(
            PHIEUMUONCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PHIEUMUONCTLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(PHIEUMUONCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PHIEUMUONCTLayout.createSequentialGroup()
                        .addGroup(PHIEUMUONCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PHIEUMUONCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel38)
                                .addComponent(jLabel40)
                                .addComponent(jLabel39))
                            .addGroup(PHIEUMUONCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnPMCTCAPNHAT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnPMCTNHAPMOI, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(PHIEUMUONCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PHIEUMUONCTLayout.createSequentialGroup()
                                .addGroup(PHIEUMUONCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPMCTMAPHIEUMUON, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                    .addComponent(txtMAPMCT)
                                    .addComponent(txtPMCTMASACH))
                                .addGap(39, 39, 39))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PHIEUMUONCTLayout.createSequentialGroup()
                                .addGroup(PHIEUMUONCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnPMCTTHEMMOI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnPMCTXOA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(50, 50, 50)))
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        PHIEUMUONCTLayout.setVerticalGroup(
            PHIEUMUONCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PHIEUMUONCTLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(PHIEUMUONCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PHIEUMUONCTLayout.createSequentialGroup()
                        .addGroup(PHIEUMUONCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel38)
                            .addComponent(txtMAPMCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PHIEUMUONCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel40)
                            .addComponent(txtPMCTMAPHIEUMUON, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PHIEUMUONCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel39)
                            .addComponent(txtPMCTMASACH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(PHIEUMUONCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPMCTNHAPMOI)
                            .addComponent(btnPMCTTHEMMOI))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PHIEUMUONCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPMCTCAPNHAT)
                            .addComponent(btnPMCTXOA)))
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );

        lblBR.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblBR.setName(""); // NOI18N
        lblBR.setOpaque(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PHIEUMUONCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lblBR, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PHIEUMUONCT, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lblBR, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 2496, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenu1.setBackground(new java.awt.Color(255, 255, 255));
        jMenu1.setText("Hệ thống");

        mitDANGXUAT.setBackground(new java.awt.Color(255, 255, 255));
        mitDANGXUAT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/icondx1.jpg"))); // NOI18N
        mitDANGXUAT.setText("Đăng xuất");
        mitDANGXUAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitDANGXUATActionPerformed(evt);
            }
        });
        jMenu1.add(mitDANGXUAT);

        mitDOIMK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/icondmk.jpg"))); // NOI18N
        mitDOIMK.setText("Đổi mật khẩu");
        mitDOIMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitDOIMKActionPerformed(evt);
            }
        });
        jMenu1.add(mitDOIMK);

        mitTHOAT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconexit1.jpg"))); // NOI18N
        mitTHOAT.setText("Thoát");
        mitTHOAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitTHOATActionPerformed(evt);
            }
        });
        jMenu1.add(mitTHOAT);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Quản lý");

        mitNHANVIEN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconnv1.jpg"))); // NOI18N
        mitNHANVIEN.setText("Nhân viên");
        mitNHANVIEN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitNHANVIENActionPerformed(evt);
            }
        });
        jMenu2.add(mitNHANVIEN);

        mitDOCGIA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/icondocgia1.jpg"))); // NOI18N
        mitDOCGIA.setText("Độc giả");
        mitDOCGIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitDOCGIAActionPerformed(evt);
            }
        });
        jMenu2.add(mitDOCGIA);

        mitSACH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconbook1.jpg"))); // NOI18N
        mitSACH.setText("Sách");
        mitSACH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitSACHActionPerformed(evt);
            }
        });
        jMenu2.add(mitSACH);

        mitTACGIA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/icontacgia1.jpg"))); // NOI18N
        mitTACGIA.setText("Tác giả");
        mitTACGIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitTACGIAActionPerformed(evt);
            }
        });
        jMenu2.add(mitTACGIA);

        mitNXB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconnxb1.jpg"))); // NOI18N
        mitNXB.setText("Nhà xuất bản");
        mitNXB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitNXBActionPerformed(evt);
            }
        });
        jMenu2.add(mitNXB);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Thống kê");

        mitPHIEUNHAP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconphieunhapsach1.jpg"))); // NOI18N
        mitPHIEUNHAP.setText("Phiếu nhập sách");
        mitPHIEUNHAP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitPHIEUNHAPActionPerformed(evt);
            }
        });
        jMenu3.add(mitPHIEUNHAP);

        mitPHIEUMUON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconphieumuon1.jpg"))); // NOI18N
        mitPHIEUMUON.setText("Phiếu mượn sách");
        mitPHIEUMUON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitPHIEUMUONActionPerformed(evt);
            }
        });
        jMenu3.add(mitPHIEUMUON);

        mitPHIEUMUONCT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconphieumuonct1.jpg"))); // NOI18N
        mitPHIEUMUONCT.setText("Phiếu mượn sách chi tiết");
        mitPHIEUMUONCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitPHIEUMUONCTActionPerformed(evt);
            }
        });
        jMenu3.add(mitPHIEUMUONCT);

        mitTHONGKE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconbdtk.jpg"))); // NOI18N
        mitTHONGKE.setText("Thống kê số liệu");
        mitTHONGKE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitTHONGKEActionPerformed(evt);
            }
        });
        jMenu3.add(mitTHONGKE);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Trợ giúp");

        mitHDSD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconhdsd1.jpg"))); // NOI18N
        mitHDSD.setText("Hướng dẫn sử dụng");
        jMenu4.add(mitHDSD);

        mitTTPB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/gt_1.png"))); // NOI18N
        mitTTPB.setText("Thông tin phiên bản");
        jMenu4.add(mitTTPB);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mitDANGXUATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitDANGXUATActionPerformed
        frmDANGNHAP frmDN;
        try {
            frmDN = new frmDANGNHAP();;
            frmDN.show();
            dispose();
        } catch (ClassNotFoundException | SQLException ex1) {
            Logger.getLogger(frmDANGNHAP.class.getName()).log(Level.SEVERE, null, ex1);
        }
    }//GEN-LAST:event_mitDANGXUATActionPerformed

    private void mitTHOATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitTHOATActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mitTHOATActionPerformed

    private void btnSACHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSACHActionPerformed
        frmSACH frmS = new frmSACH();
        frmS.show();
        dispose();
    }//GEN-LAST:event_btnSACHActionPerformed

    private void btnPHIEUNHAPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPHIEUNHAPActionPerformed
        frmPHIEUNHAP frmPN;
        frmPN = new frmPHIEUNHAP();
        frmPN.show();
        dispose();
    }//GEN-LAST:event_btnPHIEUNHAPActionPerformed

    private void btnPHIEUMUONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPHIEUMUONActionPerformed
        frmPHIEUMUON frmPM = new frmPHIEUMUON();
        frmPM.show();
        dispose();
    }//GEN-LAST:event_btnPHIEUMUONActionPerformed

    private void btnPHIEUMUONCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPHIEUMUONCTActionPerformed
        frmPHIEUMUONCT frmPMCT = new frmPHIEUMUONCT();
        frmPMCT.show();
        dispose();
    }//GEN-LAST:event_btnPHIEUMUONCTActionPerformed

    private void mitNHANVIENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitNHANVIENActionPerformed
        frmNNHANVIEN frmNV = new frmNNHANVIEN();
        frmNV.show();
        dispose();
    }//GEN-LAST:event_mitNHANVIENActionPerformed

    private void mitDOCGIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitDOCGIAActionPerformed
        frmDOCGIA frmDG = new frmDOCGIA();
        frmDG.show();
        dispose();
    }//GEN-LAST:event_mitDOCGIAActionPerformed

    private void mitSACHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitSACHActionPerformed
        frmSACH frmS = new frmSACH();
        frmS.show();
        dispose();
    }//GEN-LAST:event_mitSACHActionPerformed

    private void mitTACGIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitTACGIAActionPerformed
        frmTACGIA frmTG = new frmTACGIA();
        frmTG.show();
        dispose();
    }//GEN-LAST:event_mitTACGIAActionPerformed

    private void mitNXBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitNXBActionPerformed
        frmNXB frmN = new frmNXB();
        frmN.show();
        dispose();
    }//GEN-LAST:event_mitNXBActionPerformed

    private void mitPHIEUNHAPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitPHIEUNHAPActionPerformed
        frmPHIEUNHAP frmPN;
        frmPN = new frmPHIEUNHAP();
        frmPN.show();
        dispose();
    }//GEN-LAST:event_mitPHIEUNHAPActionPerformed

    private void mitPHIEUMUONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitPHIEUMUONActionPerformed
        frmPHIEUMUON frmPM = new frmPHIEUMUON();
        frmPM.show();
        dispose();
    }//GEN-LAST:event_mitPHIEUMUONActionPerformed

    private void mitPHIEUMUONCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitPHIEUMUONCTActionPerformed
        frmPHIEUMUONCT frmPMCT = new frmPHIEUMUONCT();
        frmPMCT.show();
        dispose();
    }//GEN-LAST:event_mitPHIEUMUONCTActionPerformed

    private void mitTHONGKEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitTHONGKEActionPerformed
        frmTHONGKE frmTK = new frmTHONGKE();
        frmTK.show();
        dispose();
    }//GEN-LAST:event_mitTHONGKEActionPerformed

    private void btnPMCTTHEMMOIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPMCTTHEMMOIActionPerformed

    }//GEN-LAST:event_btnPMCTTHEMMOIActionPerformed

    private void btnPMCTCAPNHATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPMCTCAPNHATActionPerformed

    }//GEN-LAST:event_btnPMCTCAPNHATActionPerformed

    private void btnPMCTXOAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPMCTXOAActionPerformed

    }//GEN-LAST:event_btnPMCTXOAActionPerformed

    private void btnPMCTSEACHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPMCTSEACHActionPerformed

    }//GEN-LAST:event_btnPMCTSEACHActionPerformed

    private void btnDANGXUATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDANGXUATActionPerformed
        frmDANGNHAP frmDN;
        try {
            frmDN = new frmDANGNHAP();;
            frmDN.show();
            dispose();
        } catch (ClassNotFoundException | SQLException ex1) {
            Logger.getLogger(frmDANGNHAP.class.getName()).log(Level.SEVERE, null, ex1);
        }
    }//GEN-LAST:event_btnDANGXUATActionPerformed

    private void mitDOIMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitDOIMKActionPerformed
        frmDOIMATKHAU frmDMK;
        try {
            frmDMK = new frmDOIMATKHAU();
            frmDMK.show();
            dispose();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(frmDANGNHAP.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mitDOIMKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPHIEUMUONCT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPHIEUMUONCT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPHIEUMUONCT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPHIEUMUONCT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPHIEUMUONCT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PHIEUMUONCT;
    private javax.swing.JButton btnDANGXUAT;
    private javax.swing.JButton btnPHIEUMUON;
    private javax.swing.JButton btnPHIEUMUONCT;
    private javax.swing.JButton btnPHIEUNHAP;
    private javax.swing.JButton btnPMCTCAPNHAT;
    private javax.swing.JButton btnPMCTNHAPMOI;
    private javax.swing.JButton btnPMCTSEACH;
    private javax.swing.JButton btnPMCTTHEMMOI;
    private javax.swing.JButton btnPMCTXOA;
    private javax.swing.JButton btnSACH;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JCheckBox ckbMAPMCT;
    private javax.swing.JCheckBox ckbPMCTMAPHIEUMUON;
    private javax.swing.JCheckBox ckbPMCTMASACH;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblBR;
    private javax.swing.JMenuItem mitDANGXUAT;
    private javax.swing.JMenuItem mitDOCGIA;
    private javax.swing.JMenuItem mitDOIMK;
    private javax.swing.JMenuItem mitHDSD;
    private javax.swing.JMenuItem mitNHANVIEN;
    private javax.swing.JMenuItem mitNXB;
    private javax.swing.JMenuItem mitPHIEUMUON;
    private javax.swing.JMenuItem mitPHIEUMUONCT;
    private javax.swing.JMenuItem mitPHIEUNHAP;
    private javax.swing.JMenuItem mitSACH;
    private javax.swing.JMenuItem mitTACGIA;
    private javax.swing.JMenuItem mitTHOAT;
    private javax.swing.JMenuItem mitTHONGKE;
    private javax.swing.JMenuItem mitTTPB;
    private javax.swing.JTable tblPHIEUMUONCHITIET;
    private javax.swing.JTextField txtMAPMCT;
    private javax.swing.JTextField txtPMCTMAPHIEUMUON;
    private javax.swing.JTextField txtPMCTMASACH;
    // End of variables declaration//GEN-END:variables

}
