/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frmQLTV;

import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Sach;
import model.SachDao;
import java.awt.Desktop;
import java.awt.HeadlessException;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.NhaXB;
import model.NhaXBDao;
import model.Tacgia;
import model.TacgiaDao;
import model.Theloai;
import model.TheloaiDao;

/**
 *
 * @author My PC
 */
public final class frmSACH extends javax.swing.JFrame {

    /**
     * Creates new form frmMENU
     */
    List<Sach> sach = new ArrayList<>();
    List<Tacgia> tacgia = new ArrayList<>();
    List<NhaXB> nhaxb = new ArrayList<>();
    List<Theloai> tloai = new ArrayList<>();
    private String hinhanh = "";
    private int currentindex;
    private int role;
    private String manv;
    private String loaisach;

    public frmSACH() {
        initComponents();
        this.setSize(1230, 615);
        lblBR.setIcon(new ImageIcon(getClass().getResource("/BR/br1-1.jpg")));
        setLocationRelativeTo(null);
        checkRole(role);
        SACH.show(true);
        LOAISACH.show(false);
        BRLS.show(false);
        lblBR.show(true);
        laydulieuSach("");
        laydulieuSach1();
        lblCR.setText((currentindex + 1) + "/" + sach.size());
    }

    public void Loaisach(String ma) {
        txtMATHELOAI.setText(ma);

    }

    // set vai trò quản lý
    public void setRole(int role) {
        this.role = role;
        checkRole(role);
    }
// set mã nhân vên

    public void setManv(String manv) {

        this.manv = manv;

    }
// kiểm tra vai trò : 1 - Quản lý , 2 - Nhân viên

    public void checkRole(int role) {
        if (role == 1) {
            mitNHANVIEN.hide();
            mitTHONGKE.hide();
        }
    }

    private void laydulieuSach(String sql) {
        try {
            tblSACH.removeAll();
            sach.clear();
            sach = SachDao.laydulieuSach(sql);
            fillToTableSach();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Tải dữ liệu lên thất bại");
        }
    }

    private void laydulieuLoaisach(String sql) {
        try {
            tloai.clear();
            tblLOAISACH.removeAll();
            tloai = TheloaiDao.laydulieuTheloai(sql);
            laydulieuLoaisach1();
            fillToTableLoaisach();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Tải dữ liệu lên thất bại");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        buttonGroup11 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btnDANGXUAT = new javax.swing.JButton();
        btnSACH = new javax.swing.JButton();
        btnPHIEUNHAP = new javax.swing.JButton();
        btnPHIEUMUON = new javax.swing.JButton();
        btnPHIEUMUONCT = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        LOAISACH = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblLOAISACH = new javax.swing.JTable();
        btnCAPNHATLS = new javax.swing.JButton();
        btnTHEMMOILS = new javax.swing.JButton();
        btnNHAPMOILS = new javax.swing.JButton();
        btnXOALS = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtMALS = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtTENLS = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        ckbMALS = new javax.swing.JCheckBox();
        ckbTENLS = new javax.swing.JCheckBox();
        btnSEACHLS = new javax.swing.JButton();
        btnEXITLS = new javax.swing.JButton();
        btnCHONLS = new javax.swing.JButton();
        BRLS = new javax.swing.JPanel();
        btnBRLS = new javax.swing.JButton();
        SACH = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSACH = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnHINHSACH = new javax.swing.JButton();
        txtMASACH = new javax.swing.JTextField();
        txtTENSACH = new javax.swing.JTextField();
        txtMATHELOAI = new javax.swing.JTextField();
        txtSACHMATG = new javax.swing.JTextField();
        txtSACHMANXB = new javax.swing.JTextField();
        txtSACHNAMXB = new javax.swing.JTextField();
        txtSACHSL = new javax.swing.JTextField();
        btnNHAPMOISACH = new javax.swing.JButton();
        btnTHEMMOISACH = new javax.swing.JButton();
        btnCAPNHATSACH = new javax.swing.JButton();
        btnXOASACH = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        ckbMASACH = new javax.swing.JCheckBox();
        ckbTENSACH = new javax.swing.JCheckBox();
        ckbLOAISACH = new javax.swing.JCheckBox();
        ckbSACHMATG = new javax.swing.JCheckBox();
        ckbSACHMANXB = new javax.swing.JCheckBox();
        btnTIMKIEMSACH = new javax.swing.JButton();
        btnPR = new javax.swing.JButton();
        btnPR1 = new javax.swing.JButton();
        btnNEXT1 = new javax.swing.JButton();
        btnNEXT = new javax.swing.JButton();
        lblCR = new javax.swing.JLabel();
        btnCHONFILE = new javax.swing.JButton();
        btnMOFILE = new javax.swing.JButton();
        txtFILE = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        lblBR = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mitDANGXUAT = new javax.swing.JMenuItem();
        mitDOIMK = new javax.swing.JMenuItem();
        mitTHOAT = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mitNHANVIEN = new javax.swing.JMenuItem();
        mitDOCGIA = new javax.swing.JMenuItem();
        mitSACH = new javax.swing.JMenuItem();
        mitTACGIA = new javax.swing.JMenuItem();
        mitNXB = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mitPHIEUNHAP = new javax.swing.JMenuItem();
        mitPHIEUMUON = new javax.swing.JMenuItem();
        mitPHIEUMUONCT = new javax.swing.JMenuItem();
        mitTHONGKE = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mitHDSD = new javax.swing.JMenuItem();
        mitTTPB = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÝ THƯ VIỆN");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setRollover(true);
        jToolBar1.setToolTipText("");

        btnDANGXUAT.setBackground(new java.awt.Color(255, 255, 255));
        btnDANGXUAT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnDANGXUAT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/icondx1.jpg"))); // NOI18N
        btnDANGXUAT.setText("Đăng xuất");
        btnDANGXUAT.setFocusable(false);
        btnDANGXUAT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDANGXUAT.setMaximumSize(new java.awt.Dimension(91, 51));
        btnDANGXUAT.setMinimumSize(new java.awt.Dimension(91, 51));
        btnDANGXUAT.setPreferredSize(new java.awt.Dimension(91, 51));
        btnDANGXUAT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDANGXUAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDANGXUATActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDANGXUAT);

        btnSACH.setBackground(new java.awt.Color(255, 255, 255));
        btnSACH.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSACH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconbook1.jpg"))); // NOI18N
        btnSACH.setText("Sách");
        btnSACH.setFocusable(false);
        btnSACH.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSACH.setMaximumSize(new java.awt.Dimension(91, 51));
        btnSACH.setMinimumSize(new java.awt.Dimension(91, 51));
        btnSACH.setPreferredSize(new java.awt.Dimension(91, 51));
        btnSACH.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSACH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSACHActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSACH);

        btnPHIEUNHAP.setBackground(new java.awt.Color(255, 255, 255));
        btnPHIEUNHAP.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnPHIEUNHAP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconphieunhapsach1.jpg"))); // NOI18N
        btnPHIEUNHAP.setText("Phiếu nhập");
        btnPHIEUNHAP.setFocusable(false);
        btnPHIEUNHAP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPHIEUNHAP.setMaximumSize(new java.awt.Dimension(91, 51));
        btnPHIEUNHAP.setMinimumSize(new java.awt.Dimension(91, 51));
        btnPHIEUNHAP.setPreferredSize(new java.awt.Dimension(91, 51));
        btnPHIEUNHAP.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPHIEUNHAP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPHIEUNHAPActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPHIEUNHAP);

        btnPHIEUMUON.setBackground(new java.awt.Color(255, 255, 255));
        btnPHIEUMUON.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnPHIEUMUON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconphieumuon1.jpg"))); // NOI18N
        btnPHIEUMUON.setText("Phiếu mượn");
        btnPHIEUMUON.setFocusable(false);
        btnPHIEUMUON.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPHIEUMUON.setMaximumSize(new java.awt.Dimension(91, 51));
        btnPHIEUMUON.setMinimumSize(new java.awt.Dimension(91, 51));
        btnPHIEUMUON.setPreferredSize(new java.awt.Dimension(91, 51));
        btnPHIEUMUON.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPHIEUMUON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPHIEUMUONActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPHIEUMUON);

        btnPHIEUMUONCT.setBackground(new java.awt.Color(255, 255, 255));
        btnPHIEUMUONCT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnPHIEUMUONCT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconphieumuonct1.jpg"))); // NOI18N
        btnPHIEUMUONCT.setText("Phiếu mượn CT");
        btnPHIEUMUONCT.setFocusable(false);
        btnPHIEUMUONCT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPHIEUMUONCT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPHIEUMUONCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPHIEUMUONCTActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPHIEUMUONCT);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.CardLayout());

        LOAISACH.setOpaque(false);

        jPanel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel5.setOpaque(false);

        tblLOAISACH.setBackground(new java.awt.Color(204, 255, 255));
        tblLOAISACH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã loại sách", "Tên loại sách"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblLOAISACH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLOAISACHMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblLOAISACH);

        btnCAPNHATLS.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCAPNHATLS.setForeground(new java.awt.Color(51, 51, 51));
        btnCAPNHATLS.setText("Cập nhật");
        btnCAPNHATLS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCAPNHATLSActionPerformed(evt);
            }
        });

        btnTHEMMOILS.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnTHEMMOILS.setForeground(new java.awt.Color(51, 51, 51));
        btnTHEMMOILS.setText("Thêm mới");
        btnTHEMMOILS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTHEMMOILSActionPerformed(evt);
            }
        });

        btnNHAPMOILS.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNHAPMOILS.setForeground(new java.awt.Color(51, 51, 51));
        btnNHAPMOILS.setText("Nhập mới");
        btnNHAPMOILS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNHAPMOILSActionPerformed(evt);
            }
        });

        btnXOALS.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnXOALS.setForeground(new java.awt.Color(51, 51, 51));
        btnXOALS.setText("Xóa");
        btnXOALS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXOALSActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 255));
        jLabel4.setText("Mã loại sách");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 255));
        jLabel9.setText("Tên loại sách");

        txtTENLS.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm kiếm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(0, 51, 255))); // NOI18N
        jPanel6.setOpaque(false);

        buttonGroup9.add(ckbMALS);
        ckbMALS.setText("Mã loại sách");

        buttonGroup9.add(ckbTENLS);
        ckbTENLS.setText("Tên loại sách");

        btnSEACHLS.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSEACHLS.setForeground(new java.awt.Color(0, 51, 255));
        btnSEACHLS.setText("SEACH");
        btnSEACHLS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSEACHLSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ckbMALS)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(ckbTENLS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSEACHLS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ckbMALS)
                .addGap(18, 18, 18)
                .addComponent(ckbTENLS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSEACHLS)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnEXITLS.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEXITLS.setForeground(new java.awt.Color(204, 0, 0));
        btnEXITLS.setText("Đóng");
        btnEXITLS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEXITLSActionPerformed(evt);
            }
        });

        btnCHONLS.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCHONLS.setForeground(new java.awt.Color(0, 51, 255));
        btnCHONLS.setText("Chọn");
        btnCHONLS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCHONLSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addGap(18, 18, 18))
                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addGap(22, 22, 22)))
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnCHONLS)
                                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txtMALS, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                                .addComponent(txtTENLS))))
                                    .addComponent(btnEXITLS))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(btnCAPNHATLS, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(btnNHAPMOILS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(13, 13, 13)))
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnXOALS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnTHEMMOILS, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnEXITLS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtMALS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtTENLS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCHONLS)
                        .addGap(13, 13, 13)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTHEMMOILS)
                            .addComponent(btnNHAPMOILS))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXOALS)
                    .addComponent(btnCAPNHATLS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout LOAISACHLayout = new javax.swing.GroupLayout(LOAISACH);
        LOAISACH.setLayout(LOAISACHLayout);
        LOAISACHLayout.setHorizontalGroup(
            LOAISACHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LOAISACHLayout.createSequentialGroup()
                .addGap(425, 425, 425)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(2391, Short.MAX_VALUE))
        );
        LOAISACHLayout.setVerticalGroup(
            LOAISACHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LOAISACHLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        jPanel2.add(LOAISACH, "card5");

        BRLS.setOpaque(false);

        btnBRLS.setPreferredSize(new java.awt.Dimension(388, 336));
        btnBRLS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBRLSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BRLSLayout = new javax.swing.GroupLayout(BRLS);
        BRLS.setLayout(BRLSLayout);
        BRLSLayout.setHorizontalGroup(
            BRLSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BRLSLayout.createSequentialGroup()
                .addGap(425, 425, 425)
                .addComponent(btnBRLS, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(2364, Short.MAX_VALUE))
        );
        BRLSLayout.setVerticalGroup(
            BRLSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BRLSLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(btnBRLS, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jPanel2.add(BRLS, "card5");

        SACH.setBackground(new java.awt.Color(255, 255, 255));
        SACH.setOpaque(false);

        tblSACH.setBackground(new java.awt.Color(204, 255, 255));
        tblSACH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã sách", "Tên sách", "Mã tác giả", "Loại sách", "Số lượng", "Mã NXB", "Năm xuất bản", "File đính kèm", "Hình ảnh"
            }
        ));
        tblSACH.setToolTipText("");
        tblSACH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSACHMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSACH);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Mã sách");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Tên sách");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Mã thể loại");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("Mã tác giả");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("Số lượng");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setText("Mã NXB");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 255));
        jLabel8.setText("Năm xuất bản");

        btnHINHSACH.setBackground(new java.awt.Color(255, 255, 255));
        btnHINHSACH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHINHSACHActionPerformed(evt);
            }
        });

        btnNHAPMOISACH.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNHAPMOISACH.setForeground(new java.awt.Color(51, 51, 51));
        btnNHAPMOISACH.setText("Nhập mới");
        btnNHAPMOISACH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNHAPMOISACHActionPerformed(evt);
            }
        });

        btnTHEMMOISACH.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnTHEMMOISACH.setForeground(new java.awt.Color(51, 51, 51));
        btnTHEMMOISACH.setText("Thêm mới");
        btnTHEMMOISACH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTHEMMOISACHActionPerformed(evt);
            }
        });

        btnCAPNHATSACH.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCAPNHATSACH.setForeground(new java.awt.Color(51, 51, 51));
        btnCAPNHATSACH.setText("Cập nhật");
        btnCAPNHATSACH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCAPNHATSACHActionPerformed(evt);
            }
        });

        btnXOASACH.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnXOASACH.setForeground(new java.awt.Color(51, 51, 51));
        btnXOASACH.setText("Xóa");
        btnXOASACH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXOASACHActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Tìm kiếm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel3.setOpaque(false);

        buttonGroup1.add(ckbMASACH);
        ckbMASACH.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ckbMASACH.setForeground(new java.awt.Color(0, 0, 255));
        ckbMASACH.setText("Mã sách");

        buttonGroup1.add(ckbTENSACH);
        ckbTENSACH.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ckbTENSACH.setForeground(new java.awt.Color(0, 0, 255));
        ckbTENSACH.setText("Tên sách");

        buttonGroup1.add(ckbLOAISACH);
        ckbLOAISACH.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ckbLOAISACH.setForeground(new java.awt.Color(0, 0, 255));
        ckbLOAISACH.setText("Loại sách");

        buttonGroup1.add(ckbSACHMATG);
        ckbSACHMATG.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ckbSACHMATG.setForeground(new java.awt.Color(0, 0, 255));
        ckbSACHMATG.setText("Tác giả");
        ckbSACHMATG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbSACHMATGActionPerformed(evt);
            }
        });

        buttonGroup1.add(ckbSACHMANXB);
        ckbSACHMANXB.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ckbSACHMANXB.setForeground(new java.awt.Color(0, 0, 255));
        ckbSACHMANXB.setText("Nhà xuất bản");

        btnTIMKIEMSACH.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnTIMKIEMSACH.setForeground(new java.awt.Color(51, 51, 51));
        btnTIMKIEMSACH.setText("SEACH");
        btnTIMKIEMSACH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTIMKIEMSACHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ckbMASACH)
                    .addComponent(ckbTENSACH)
                    .addComponent(ckbLOAISACH)
                    .addComponent(ckbSACHMATG)
                    .addComponent(ckbSACHMANXB))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(btnTIMKIEMSACH)
                .addGap(46, 46, 46))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(ckbMASACH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ckbTENSACH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ckbLOAISACH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ckbSACHMATG)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ckbSACHMANXB)
                .addGap(18, 18, 18)
                .addComponent(btnTIMKIEMSACH)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        btnPR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/forward-icon1.png"))); // NOI18N
        btnPR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPRActionPerformed(evt);
            }
        });

        btnPR1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/skip-forward-icon0.png"))); // NOI18N
        btnPR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPR1ActionPerformed(evt);
            }
        });

        btnNEXT1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/skip-forward-icon1.png"))); // NOI18N
        btnNEXT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNEXT1ActionPerformed(evt);
            }
        });

        btnNEXT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/forward-icon.png"))); // NOI18N
        btnNEXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNEXTActionPerformed(evt);
            }
        });

        lblCR.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lblCR.setForeground(new java.awt.Color(204, 0, 0));
        lblCR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnCHONFILE.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCHONFILE.setForeground(new java.awt.Color(0, 51, 255));
        btnCHONFILE.setText("Chọn file");
        btnCHONFILE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCHONFILEActionPerformed(evt);
            }
        });

        btnMOFILE.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnMOFILE.setForeground(new java.awt.Color(0, 51, 255));
        btnMOFILE.setText("Mở");
        btnMOFILE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMOFILEActionPerformed(evt);
            }
        });

        txtFILE.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 255));
        jButton1.setText("Thể loại");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SACHLayout = new javax.swing.GroupLayout(SACH);
        SACH.setLayout(SACHLayout);
        SACHLayout.setHorizontalGroup(
            SACHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SACHLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(SACHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(SACHLayout.createSequentialGroup()
                        .addGroup(SACHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(29, 29, 29)
                        .addGroup(SACHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(SACHLayout.createSequentialGroup()
                                .addGroup(SACHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(SACHLayout.createSequentialGroup()
                                        .addGap(214, 214, 214)
                                        .addComponent(btnPR, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(34, 34, 34)
                                        .addComponent(lblCR, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(34, 34, 34)
                                        .addComponent(btnNEXT, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(37, 37, 37)
                                        .addComponent(btnNEXT1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(SACHLayout.createSequentialGroup()
                                        .addGroup(SACHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtMASACH, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtTENSACH, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(SACHLayout.createSequentialGroup()
                                                .addGap(140, 140, 140)
                                                .addComponent(btnPR1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SACHLayout.createSequentialGroup()
                                                .addComponent(txtMATHELOAI, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButton1)))
                                        .addGap(34, 34, 34)
                                        .addGroup(SACHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(SACHLayout.createSequentialGroup()
                                                .addGroup(SACHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel5)
                                                    .addComponent(jLabel7))
                                                .addGroup(SACHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(SACHLayout.createSequentialGroup()
                                                        .addGap(42, 42, 42)
                                                        .addComponent(txtSACHMATG, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addGroup(SACHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel8)
                                                            .addComponent(jLabel6))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addGroup(SACHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(txtSACHNAMXB, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                                                            .addComponent(txtSACHSL)))
                                                    .addGroup(SACHLayout.createSequentialGroup()
                                                        .addGap(44, 44, 44)
                                                        .addGroup(SACHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(txtSACHMANXB, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SACHLayout.createSequentialGroup()
                                                                .addGap(0, 217, Short.MAX_VALUE)
                                                                .addComponent(btnMOFILE, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                            .addGroup(SACHLayout.createSequentialGroup()
                                                .addComponent(btnCHONFILE)
                                                .addGap(10, 10, 10)
                                                .addComponent(txtFILE, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(30, 30, 30))
                            .addGroup(SACHLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(btnNHAPMOISACH, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(SACHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(SACHLayout.createSequentialGroup()
                                        .addGap(53, 53, 53)
                                        .addComponent(btnTHEMMOISACH))
                                    .addGroup(SACHLayout.createSequentialGroup()
                                        .addGap(222, 222, 222)
                                        .addComponent(btnCAPNHATSACH, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnXOASACH, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61)))
                        .addComponent(btnHINHSACH, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(2023, Short.MAX_VALUE))
        );
        SACHLayout.setVerticalGroup(
            SACHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SACHLayout.createSequentialGroup()
                .addGroup(SACHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SACHLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(SACHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtMASACH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSACHMATG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(txtSACHSL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(27, 27, 27)
                        .addGroup(SACHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7)
                            .addComponent(txtTENSACH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSACHMANXB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(txtSACHNAMXB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(SACHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(SACHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(txtMATHELOAI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnCHONFILE)
                                .addComponent(txtFILE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton1))
                            .addComponent(btnMOFILE))
                        .addGap(24, 24, 24)
                        .addGroup(SACHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNHAPMOISACH)
                            .addComponent(btnTHEMMOISACH)
                            .addComponent(btnCAPNHATSACH)
                            .addComponent(btnXOASACH))
                        .addGap(18, 18, 18)
                        .addGroup(SACHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNEXT)
                            .addComponent(btnNEXT1)
                            .addComponent(btnPR)
                            .addComponent(btnPR1)
                            .addComponent(lblCR, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(SACHLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SACHLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(btnHINHSACH, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jPanel2.add(SACH, "card3");

        lblBR.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBR.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblBR.setName(""); // NOI18N
        lblBR.setOpaque(true);
        jPanel2.add(lblBR, "card11");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenu1.setBackground(new java.awt.Color(255, 255, 255));
        jMenu1.setText("Hệ thống");

        mitDANGXUAT.setBackground(new java.awt.Color(255, 255, 255));
        mitDANGXUAT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/icondx1.jpg"))); // NOI18N
        mitDANGXUAT.setText("Đăng xuất");
        mitDANGXUAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitDANGXUATActionPerformed(evt);
            }
        });
        jMenu1.add(mitDANGXUAT);

        mitDOIMK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/icondmk.jpg"))); // NOI18N
        mitDOIMK.setText("Đổi mật khẩu");
        mitDOIMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitDOIMKActionPerformed(evt);
            }
        });
        jMenu1.add(mitDOIMK);

        mitTHOAT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconexit1.jpg"))); // NOI18N
        mitTHOAT.setText("Thoát");
        mitTHOAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitTHOATActionPerformed(evt);
            }
        });
        jMenu1.add(mitTHOAT);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Quản lý");

        mitNHANVIEN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconnv1.jpg"))); // NOI18N
        mitNHANVIEN.setText("Nhân viên");
        mitNHANVIEN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitNHANVIENActionPerformed(evt);
            }
        });
        jMenu2.add(mitNHANVIEN);

        mitDOCGIA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/icondocgia1.jpg"))); // NOI18N
        mitDOCGIA.setText("Độc giả");
        mitDOCGIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitDOCGIAActionPerformed(evt);
            }
        });
        jMenu2.add(mitDOCGIA);

        mitSACH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconbook1.jpg"))); // NOI18N
        mitSACH.setText("Sách");
        mitSACH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitSACHActionPerformed(evt);
            }
        });
        jMenu2.add(mitSACH);

        mitTACGIA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/icontacgia1.jpg"))); // NOI18N
        mitTACGIA.setText("Tác giả");
        mitTACGIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitTACGIAActionPerformed(evt);
            }
        });
        jMenu2.add(mitTACGIA);

        mitNXB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconnxb1.jpg"))); // NOI18N
        mitNXB.setText("Nhà xuất bản");
        mitNXB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitNXBActionPerformed(evt);
            }
        });
        jMenu2.add(mitNXB);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Thống kê");

        mitPHIEUNHAP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconphieunhapsach1.jpg"))); // NOI18N
        mitPHIEUNHAP.setText("Phiếu nhập sách");
        mitPHIEUNHAP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitPHIEUNHAPActionPerformed(evt);
            }
        });
        jMenu3.add(mitPHIEUNHAP);

        mitPHIEUMUON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconphieumuon1.jpg"))); // NOI18N
        mitPHIEUMUON.setText("Phiếu mượn sách");
        mitPHIEUMUON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitPHIEUMUONActionPerformed(evt);
            }
        });
        jMenu3.add(mitPHIEUMUON);

        mitPHIEUMUONCT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconphieumuonct1.jpg"))); // NOI18N
        mitPHIEUMUONCT.setText("Phiếu mượn sách chi tiết");
        mitPHIEUMUONCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitPHIEUMUONCTActionPerformed(evt);
            }
        });
        jMenu3.add(mitPHIEUMUONCT);

        mitTHONGKE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconbdtk.jpg"))); // NOI18N
        mitTHONGKE.setText("Thống kê số liệu");
        mitTHONGKE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitTHONGKEActionPerformed(evt);
            }
        });
        jMenu3.add(mitTHONGKE);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Trợ giúp");

        mitHDSD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconhdsd1.jpg"))); // NOI18N
        mitHDSD.setText("Hướng dẫn sử dụng");
        jMenu4.add(mitHDSD);

        mitTTPB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/gt_1.png"))); // NOI18N
        mitTTPB.setText("Thông tin phiên bản");
        jMenu4.add(mitTTPB);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ckbSACHMATGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbSACHMATGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbSACHMATGActionPerformed

    private void mitDANGXUATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitDANGXUATActionPerformed
        frmDANGNHAP frmDN;
        try {
            frmDN = new frmDANGNHAP();;
            frmDN.show();
            dispose();
        } catch (ClassNotFoundException | SQLException ex1) {
            Logger.getLogger(frmDANGNHAP.class.getName()).log(Level.SEVERE, null, ex1);
        }
    }//GEN-LAST:event_mitDANGXUATActionPerformed

    private void mitTHOATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitTHOATActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mitTHOATActionPerformed

    private void btnSACHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSACHActionPerformed
        frmSACH frmS = new frmSACH();
        frmS.show();
        dispose();
    }//GEN-LAST:event_btnSACHActionPerformed

    private void btnPHIEUNHAPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPHIEUNHAPActionPerformed
        frmPHIEUNHAP frmPN;
        frmPN = new frmPHIEUNHAP();
        frmPN.show();
        dispose();
    }//GEN-LAST:event_btnPHIEUNHAPActionPerformed

    private void btnPHIEUMUONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPHIEUMUONActionPerformed
        frmPHIEUMUON frmPM = new frmPHIEUMUON();
        frmPM.show();
        dispose();
    }//GEN-LAST:event_btnPHIEUMUONActionPerformed

    private void btnPHIEUMUONCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPHIEUMUONCTActionPerformed
        frmPHIEUMUONCT frmPMCT = new frmPHIEUMUONCT();
        frmPMCT.show();
        dispose();
    }//GEN-LAST:event_btnPHIEUMUONCTActionPerformed

    private void mitNHANVIENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitNHANVIENActionPerformed
        frmNNHANVIEN frmNV = new frmNNHANVIEN();
        frmNV.show();
        dispose();
    }//GEN-LAST:event_mitNHANVIENActionPerformed

    private void mitDOCGIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitDOCGIAActionPerformed
        frmDOCGIA frmDG = new frmDOCGIA();
        frmDG.show();
        dispose();
    }//GEN-LAST:event_mitDOCGIAActionPerformed

    private void mitSACHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitSACHActionPerformed
        frmSACH frmS = new frmSACH();
        frmS.show();
        dispose();
    }//GEN-LAST:event_mitSACHActionPerformed

    private void mitTACGIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitTACGIAActionPerformed
        frmTACGIA frmTG = new frmTACGIA();
        frmTG.show();
        dispose();
    }//GEN-LAST:event_mitTACGIAActionPerformed

    private void mitNXBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitNXBActionPerformed
        frmNXB frmN = new frmNXB();
        frmN.show();
        dispose();
    }//GEN-LAST:event_mitNXBActionPerformed

    private void mitPHIEUNHAPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitPHIEUNHAPActionPerformed
        frmPHIEUNHAP frmPN;
        frmPN = new frmPHIEUNHAP();
        frmPN.show();
        dispose();
    }//GEN-LAST:event_mitPHIEUNHAPActionPerformed

    private void mitPHIEUMUONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitPHIEUMUONActionPerformed
        frmPHIEUMUON frmPM = new frmPHIEUMUON();
        frmPM.show();
        dispose();
    }//GEN-LAST:event_mitPHIEUMUONActionPerformed

    private void mitPHIEUMUONCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitPHIEUMUONCTActionPerformed
        frmPHIEUMUONCT frmPMCT = new frmPHIEUMUONCT();
        frmPMCT.show();
        dispose();
    }//GEN-LAST:event_mitPHIEUMUONCTActionPerformed

    private void mitTHONGKEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitTHONGKEActionPerformed
        frmTHONGKE frmTK = new frmTHONGKE();
        frmTK.show();
        dispose();
    }//GEN-LAST:event_mitTHONGKEActionPerformed

    private void btnTHEMMOISACHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTHEMMOISACHActionPerformed
        try {
            kiemloisach();
            themSach();
            laydulieuSach("");
            lblCR.setText((currentindex + 1) + "/" + sach.size());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Thêm sách thất bại");
        }
    }//GEN-LAST:event_btnTHEMMOISACHActionPerformed

    private void btnCHONFILEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCHONFILEActionPerformed
        JFileChooser fch = new JFileChooser("src\\FILE\\");
        int result = fch.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            try {
                txtFILE.setText(fch.getSelectedFile().getPath());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Lỗi chọn file");
            }
        }
    }//GEN-LAST:event_btnCHONFILEActionPerformed

    private void btnHINHSACHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHINHSACHActionPerformed
        JFileChooser fch = new JFileChooser();
        int result = fch.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            try {
                //Lấy tên hình ảnh sách
                btnHINHSACH.setIcon(new ImageIcon(fch.getSelectedFile().getPath()));
                this.hinhanh = fch.getSelectedFile().getName();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Lỗi chọn hình");
            }
        }
    }//GEN-LAST:event_btnHINHSACHActionPerformed

    private void tblSACHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSACHMouseClicked
        try {
            Sach s = sach.get(tblSACH.getSelectedRow());
            txtMASACH.setText(s.getMasach());
            txtTENSACH.setText(s.getTensach());
            txtSACHMATG.setText(s.getMatacgia());
            txtMATHELOAI.setText(s.getLoai());
            txtSACHSL.setText(Integer.toString(s.getSoluong()));
            txtSACHMANXB.setText(s.getManxb());
            txtSACHNAMXB.setText(Integer.toString(s.getNamxb()));
            txtFILE.setText(s.getFiles());
            btnHINHSACH.setIcon(new ImageIcon(getClass().getResource("/IMG/" + s.getHinhanh())));
            this.hinhanh = s.getHinhanh();
            currentindex = tblSACH.getSelectedRow() + 1;
            lblCR.setText(tblSACH.getSelectedRow() + 1 + "/" + sach.size());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Dữ liệu trống");
        }
    }//GEN-LAST:event_tblSACHMouseClicked

    private void btnCAPNHATSACHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCAPNHATSACHActionPerformed
        if (txtMASACH.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã sách");
            return;
        }
        try {
            boolean ckloi = false;
            boolean kt = kiemloisach();
            if (kt == false) {
                return;
            } else {

            }
            boolean ckmasach = false;
            for (Sach s : sach) {
                if (s.getMasach().equals(txtMASACH.getText())) {
                    ckmasach = true;
                    break;
                }
            }
            if (!ckmasach) {
                JOptionPane.showMessageDialog(this, "Mã sách không tồn tại");
                return;
            }
            capnhatSach();
            laydulieuSach("");
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this, "Cập nhật sách thất bại");
        } catch (SQLException ex) {
            Logger.getLogger(frmSACH.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCAPNHATSACHActionPerformed

    private void btnXOASACHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXOASACHActionPerformed
        if (txtMASACH.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã sách");
            return;
        }
        try {
            boolean ckmasach = false;
            for (Sach s : sach) {
                if (s.getMasach().equals(txtMASACH.getText())) {
                    ckmasach = true;
                    break;
                }
            }
            if (!ckmasach) {
                JOptionPane.showMessageDialog(this, "Mã sách không tồn tại");
                return;
            }
            xoaSach();
            laydulieuSach("");
            if (!sach.isEmpty()) {
                currentindex = 0;
                laydulieuSach1();
            }
            lblCR.setText((currentindex + 1) + "/" + sach.size());
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this, "Xóa sách thất bại");
        }
    }//GEN-LAST:event_btnXOASACHActionPerformed

    private void btnPRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPRActionPerformed
        try {
            currentindex--;
            if (currentindex < 0) {
                currentindex = sach.size() - 1;
            }
            lblCR.setText((currentindex + 1) + "/" + sach.size());
            laydulieuSach1();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Không có dữ liệu");
        }
    }//GEN-LAST:event_btnPRActionPerformed

    private void btnPR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPR1ActionPerformed
        try {
            currentindex = 0;
            lblCR.setText((currentindex + 1) + "/" + sach.size());
            laydulieuSach1();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Không có dữ liệu");
        }
    }//GEN-LAST:event_btnPR1ActionPerformed

    private void btnNEXT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNEXT1ActionPerformed
        try {
            currentindex = sach.size() - 1;
            lblCR.setText((currentindex + 1) + "/" + sach.size());
            laydulieuSach1();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Không có dữ liệu");
        }
    }//GEN-LAST:event_btnNEXT1ActionPerformed

    private void btnNEXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNEXTActionPerformed
        try {
            currentindex++;
            if (currentindex > (sach.size() - 1)) {
                currentindex = 0;
            }
            lblCR.setText((currentindex + 1) + "/" + sach.size());
            laydulieuSach1();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Không có dữ liệu");
        }
    }//GEN-LAST:event_btnNEXTActionPerformed

    private void btnMOFILEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMOFILEActionPerformed
        if (txtFILE.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn file");
            return;
        }
        try {
            if (Desktop.isDesktopSupported()) {
                Desktop.getDesktop().open(new File(txtFILE.getText()));
            }
        } catch (IOException ioe) {
        }
    }//GEN-LAST:event_btnMOFILEActionPerformed

    private void btnTIMKIEMSACHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTIMKIEMSACHActionPerformed
        timkiemSach();
    }//GEN-LAST:event_btnTIMKIEMSACHActionPerformed

    private void btnNHAPMOISACHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNHAPMOISACHActionPerformed
        txtMASACH.setText("");
        txtTENSACH.setText("");
        txtSACHMATG.setText("");
        txtMATHELOAI.setText("");
        txtSACHSL.setText("");
        txtSACHMANXB.setText("");
        txtSACHNAMXB.setText("");
        txtFILE.setText("");
        btnHINHSACH.setIcon(new ImageIcon(getClass().getResource("")));
        this.hinhanh = "";
    }//GEN-LAST:event_btnNHAPMOISACHActionPerformed

    private void btnDANGXUATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDANGXUATActionPerformed
        frmDANGNHAP frmDN;
        try {
            frmDN = new frmDANGNHAP();;
            frmDN.show();
            dispose();
        } catch (ClassNotFoundException | SQLException ex1) {
            Logger.getLogger(frmDANGNHAP.class.getName()).log(Level.SEVERE, null, ex1);
        }
    }//GEN-LAST:event_btnDANGXUATActionPerformed

    private void mitDOIMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitDOIMKActionPerformed
        frmDOIMATKHAU frmDMK;
        try {
            frmDMK = new frmDOIMATKHAU();
            frmDMK.show();
            dispose();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(frmDANGNHAP.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mitDOIMKActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        laydulieuLoaisach("");
        LOAISACH.show(true);
        BRLS.show(true);
        SACH.disable();
        btnBRLS.setIcon(new ImageIcon(getClass().getResource("/BR/brtl.jpg")));

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnNHAPMOILSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNHAPMOILSActionPerformed
        txtMALS.setText("");
        txtTENLS.setText("");
    }//GEN-LAST:event_btnNHAPMOILSActionPerformed

    private void btnEXITLSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEXITLSActionPerformed
        LOAISACH.show(false);
        BRLS.show(false);
    }//GEN-LAST:event_btnEXITLSActionPerformed

    private void btnCHONLSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCHONLSActionPerformed
        LOAISACH.show(false);
        BRLS.show(false);
        Loaisach(txtMALS.getText());
    }//GEN-LAST:event_btnCHONLSActionPerformed

    private void btnBRLSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBRLSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBRLSActionPerformed

    private void tblLOAISACHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLOAISACHMouseClicked
        try {
            Theloai ls = tloai.get(tblLOAISACH.getSelectedRow());
            txtMALS.setText(ls.getMatl());
            txtTENLS.setText(ls.getTentl());
            currentindex = tblSACH.getSelectedRow() + 1;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Dữ liệu trống");
        }
    }//GEN-LAST:event_tblLOAISACHMouseClicked

    private void btnTHEMMOILSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTHEMMOILSActionPerformed

        if (kiemtraloiLS() == false) {
            return;
        } else {
        }
        themmoiLoaisach();
        laydulieuLoaisach("");
    }//GEN-LAST:event_btnTHEMMOILSActionPerformed

    private void btnCAPNHATLSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCAPNHATLSActionPerformed
        if (txtMALS.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã loại sách");
            return;
        }
        if (kiemtraloiLS() == false) {
            return;
        } else {
        }
        capnhatLoaisach();
        laydulieuLoaisach("");
    }//GEN-LAST:event_btnCAPNHATLSActionPerformed

    private void btnXOALSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXOALSActionPerformed
        if (txtMALS.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã loại sách");
            return;
        }
        boolean ckmals = false;
        for (Theloai ls : tloai) {
            if (ls.getMatl().equals(txtMALS.getText())) {
                ckmals = true;
                break;
            }
        }
        if (!ckmals) {
            JOptionPane.showMessageDialog(this, "Mã loại sách không tồn tại");
            return;
        }
        xoaLoaisach();
        laydulieuLoaisach("");
    }//GEN-LAST:event_btnXOALSActionPerformed

    private void btnSEACHLSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSEACHLSActionPerformed
        timkiemLoaisach();
    }//GEN-LAST:event_btnSEACHLSActionPerformed

    private void fillToTableSach() {
        DefaultTableModel model = (DefaultTableModel) tblSACH.getModel();
        model.setRowCount(0);
        for (Sach s : sach) {
            Object[] row = new Object[]{s.getMasach(), s.getTensach(), s.getMatacgia(), s.getLoai(), s.getSoluong(), s.getManxb(), s.getNamxb(), s.getFiles(), s.getHinhanh()};
            model.addRow(row);
        }
    }

    private void fillToTableLoaisach() {
        DefaultTableModel model = (DefaultTableModel) tblLOAISACH.getModel();
        model.setRowCount(0);
        for (Theloai tl : tloai) {
            Object[] row = new Object[]{tl.getMatl(), tl.getTentl()};
            model.addRow(row);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSACH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSACH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSACH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSACH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSACH().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BRLS;
    private javax.swing.JPanel LOAISACH;
    private javax.swing.JPanel SACH;
    private javax.swing.JButton btnBRLS;
    private javax.swing.JButton btnCAPNHATLS;
    private javax.swing.JButton btnCAPNHATSACH;
    private javax.swing.JButton btnCHONFILE;
    private javax.swing.JButton btnCHONLS;
    private javax.swing.JButton btnDANGXUAT;
    private javax.swing.JButton btnEXITLS;
    private javax.swing.JButton btnHINHSACH;
    private javax.swing.JButton btnMOFILE;
    private javax.swing.JButton btnNEXT;
    private javax.swing.JButton btnNEXT1;
    private javax.swing.JButton btnNHAPMOILS;
    private javax.swing.JButton btnNHAPMOISACH;
    private javax.swing.JButton btnPHIEUMUON;
    private javax.swing.JButton btnPHIEUMUONCT;
    private javax.swing.JButton btnPHIEUNHAP;
    private javax.swing.JButton btnPR;
    private javax.swing.JButton btnPR1;
    private javax.swing.JButton btnSACH;
    private javax.swing.JButton btnSEACHLS;
    private javax.swing.JButton btnTHEMMOILS;
    private javax.swing.JButton btnTHEMMOISACH;
    private javax.swing.JButton btnTIMKIEMSACH;
    private javax.swing.JButton btnXOALS;
    private javax.swing.JButton btnXOASACH;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup11;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JCheckBox ckbLOAISACH;
    private javax.swing.JCheckBox ckbMALS;
    private javax.swing.JCheckBox ckbMASACH;
    private javax.swing.JCheckBox ckbSACHMANXB;
    private javax.swing.JCheckBox ckbSACHMATG;
    private javax.swing.JCheckBox ckbTENLS;
    private javax.swing.JCheckBox ckbTENSACH;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblBR;
    private javax.swing.JLabel lblCR;
    private javax.swing.JMenuItem mitDANGXUAT;
    private javax.swing.JMenuItem mitDOCGIA;
    private javax.swing.JMenuItem mitDOIMK;
    private javax.swing.JMenuItem mitHDSD;
    private javax.swing.JMenuItem mitNHANVIEN;
    private javax.swing.JMenuItem mitNXB;
    private javax.swing.JMenuItem mitPHIEUMUON;
    private javax.swing.JMenuItem mitPHIEUMUONCT;
    private javax.swing.JMenuItem mitPHIEUNHAP;
    private javax.swing.JMenuItem mitSACH;
    private javax.swing.JMenuItem mitTACGIA;
    private javax.swing.JMenuItem mitTHOAT;
    private javax.swing.JMenuItem mitTHONGKE;
    private javax.swing.JMenuItem mitTTPB;
    private javax.swing.JTable tblLOAISACH;
    private javax.swing.JTable tblSACH;
    private javax.swing.JTextField txtFILE;
    private javax.swing.JTextField txtMALS;
    private javax.swing.JTextField txtMASACH;
    private javax.swing.JTextField txtMATHELOAI;
    private javax.swing.JTextField txtSACHMANXB;
    private javax.swing.JTextField txtSACHMATG;
    private javax.swing.JTextField txtSACHNAMXB;
    private javax.swing.JTextField txtSACHSL;
    private javax.swing.JTextField txtTENLS;
    private javax.swing.JTextField txtTENSACH;
    // End of variables declaration//GEN-END:variables

    public void themSach() throws SQLException {
        String masach = null;
        int a;
        AD:
        for (int i = 1; i < 1000; i++) {
            a = i;
            String b = Integer.toString(a);
            if (b.length() == 1) {
                masach = "S00" + a;
            } else if (b.length() == 2) {
                masach = "S0" + a;
            } else if (b.length() > 2) {
                masach = "S" + a;
            } else {
            }
            boolean khIsExixst = false;
            for (Sach s : sach) {
                if (s.getMasach().equals(masach)) {
                    khIsExixst = true;
                    break;
                }
            }
            if (!khIsExixst) {
                break;
            }
        }

        String tensach = txtTENSACH.getText();
        String matg = txtSACHMATG.getText();
        String theloai = txtMATHELOAI.getText();
        String soluong = txtSACHSL.getText();
        String manxb = txtSACHMANXB.getText();
        String namxb = txtSACHNAMXB.getText();
        String file1 = txtFILE.getText();
        String hinh1 = this.hinhanh;
        int sl = Integer.parseInt(soluong);
        int namxb1 = Integer.parseInt(namxb);
        Sach s = new Sach(masach, tensach, hinh1, matg, theloai, sl, manxb, namxb1, file1);
        SachDao.themSach(s);
        JOptionPane.showMessageDialog(this, "Thêm sách thành công");
    }

    public void capnhatSach() {
        String masach = txtMASACH.getText();
        String tensach = txtTENSACH.getText();
        String matg = txtSACHMATG.getText();
        String theloai = txtMATHELOAI.getText();
        String soluong = txtSACHSL.getText();
        String manxb = txtSACHMANXB.getText();
        String namxb = txtSACHNAMXB.getText();
        String file1 = txtFILE.getText();
        String hinh1 = this.hinhanh;
        int sl = Integer.parseInt(soluong);
        int namxb1 = Integer.parseInt(namxb);
        boolean khIsExixst = false;
        for (Sach s : sach) {
            if (s.getMasach().equals(masach)) {
                khIsExixst = true;
                break;
            }
        }
        if (!khIsExixst) {
            JOptionPane.showMessageDialog(this, "Mã sách không tồn tại");
            return;
        }
        Sach s = new Sach(masach, tensach, hinh1, matg, theloai, sl, manxb, namxb1, file1);
        SachDao.capnhatSach(s);
        JOptionPane.showMessageDialog(this, "Cập nhật thành công");
    }

    public void xoaSach() {
        String masach = txtMASACH.getText();
        boolean khIsExixst = false;
        for (Sach s : sach) {
            if (s.getMasach().equals(masach)) {
                khIsExixst = true;
                break;
            }
        }
        if (!khIsExixst) {
            JOptionPane.showMessageDialog(this, "Mã sách không tồn tại");
            return;
        }
        SachDao.xoaSach(masach);
        JOptionPane.showMessageDialog(this, "Xóa sách thành công");
    }

    public void timkiemSach() {
        String sql = "";
        if (ckbMASACH.isSelected()) {
            sql = "Where masach like '%" + txtMASACH.getText() + "%'";
        } else if (ckbTENSACH.isSelected()) {
            sql = "Where tensach like N'%" + txtTENSACH.getText() + "%'";
        } else if (ckbLOAISACH.isSelected()) {
            sql = "Where matl like N'%" + txtMATHELOAI.getText() + "%'";
        } else if (ckbSACHMATG.isSelected()) {
            sql = "Where matacgia like '%" + txtSACHMATG.getText() + "%'";
        } else if (ckbSACHMANXB.isSelected()) {
            sql = "Where manxb like '%" + txtSACHMANXB.getText() + "%'";
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn thuộc tính tìm kiếm");
        }
        laydulieuSach(sql);
        laydulieuSach1();
    }

    private void laydulieuSach1() {
        try {
            if (sach.size() == 1) {
                this.currentindex = 0;
            }
            Sach s = sach.get(currentindex);
            txtMASACH.setText(s.getMasach());
            txtTENSACH.setText(s.getTensach());
            txtSACHMATG.setText(s.getMatacgia());
            txtMATHELOAI.setText(s.getLoai());
            txtSACHSL.setText(Integer.toString(s.getSoluong()));
            txtSACHMANXB.setText(s.getManxb());
            txtSACHNAMXB.setText(Integer.toString(s.getNamxb()));
            txtFILE.setText(s.getFiles());
            btnHINHSACH.setIcon(new ImageIcon(getClass().getResource("/IMG/" + s.getHinhanh())));
            this.hinhanh = s.getHinhanh();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Dữ liệu trống");
        }
    }

    private boolean kiemloisach() throws SQLException {
        if (txtTENSACH.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên sách");
            return false;
        } else if (txtSACHMATG.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã tác giả");
            return false;
        } else if (txtMATHELOAI.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập thể loại sách");
            return false;
        } else if (txtSACHSL.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số lượng sách");
            return false;
        } else if (txtSACHMANXB.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã nhà xuất bản");
            return false;
        } else if (txtSACHNAMXB.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập năm xuất bản");
            return false;
        } else if (this.hinhanh.equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn hình ảnh");
            return false;
        } else {
            try {
                int sl = Integer.parseInt(txtSACHSL.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập số lượng sách bằng số");
            }
            try {
                int sl = Integer.parseInt(txtSACHNAMXB.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập năm xuất bản sách bằng số");
            }
        }
        tacgia = TacgiaDao.laydulieuTacgia("");
        boolean ckmatg = false;
        for (Tacgia tg : tacgia) {
            if (tg.getMatacgia().equals(txtSACHMATG.getText())) {
                ckmatg = true;
                break;
            }
        }
        if (!ckmatg) {
            JOptionPane.showMessageDialog(this, "Mã tác giả không tồn tại");
            return false;
        }
        nhaxb = NhaXBDao.laydulieuNhaXB("");
        boolean ckmanxb = false;
        for (NhaXB n : nhaxb) {
            if (n.getManxb().equals(txtSACHMANXB.getText())) {
                ckmanxb = true;
                break;
            }
        }
        if (!ckmanxb) {
            JOptionPane.showMessageDialog(this, "Mã NXB không tồn tại");
            return false;
        }
        tloai = TheloaiDao.laydulieuTheloai("");
        boolean ckmatl = false;
        for (Theloai tl : tloai) {
            if (tl.getMatl().equals(txtMATHELOAI.getText())) {
                ckmatl = true;
                break;
            }
        }
        if (!ckmatl) {
            JOptionPane.showMessageDialog(this, "Mã loại sách không tồn tại");
            return false;
        }
        return true;
    }

    private void laydulieuLoaisach1() {
        try {
            this.currentindex = 0;
            if (tloai.size() == 1) {
                this.currentindex = 0;
            }
            Theloai ls = tloai.get(currentindex);
            txtMALS.setText(ls.getMatl());
            txtTENLS.setText(ls.getTentl());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Dữ liệu trống");
        }
    }

    private void themmoiLoaisach() {
        String matl = null;
        int a;
        AD:
        for (int i = 1; i < 1000; i++) {
            a = i;
            String b = Integer.toString(a);
            if (b.length() == 1) {
                matl = "TL00" + a;
            } else if (b.length() == 2) {
                matl = "TL0" + a;
            } else if (b.length() > 2) {
                matl = "TL" + a;
            } else {
            }
            boolean khIsExixst = false;
            for (Theloai tl : tloai) {
                if (tl.getMatl().equals(matl)) {
                    khIsExixst = true;
                    break;
                }
            }
            if (!khIsExixst) {
                break;
            }
        }
        String tenls = txtTENLS.getText();
        Theloai tl = new Theloai(matl, tenls);
        TheloaiDao.themTheloai(tl);
        JOptionPane.showMessageDialog(this, "Thêm loại sách thành công");
    }

    private void capnhatLoaisach() {
        String mals = txtMALS.getText();
        String tenls = txtTENLS.getText();
        Theloai tl = new Theloai(mals, tenls);
        TheloaiDao.capnhatTheloai(tl);
        JOptionPane.showMessageDialog(this, "Cập nhật loại sách thành công");
    }

    private void xoaLoaisach() {
        String mals = txtMALS.getText();
        TheloaiDao.xoaTheloai(mals);
        JOptionPane.showMessageDialog(this, "Xóa loại sách thành công");
    }

    private boolean kiemtraloiLS() {
        if (txtTENLS.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên loại sách");
            return false;
        } else {
            List<Theloai> tl = new ArrayList<>();
            try {
                String sql = "where tentl like N'" + txtTENLS.getText().trim() + "'";
                tl = TheloaiDao.laydulieuTheloai(sql);
            } catch (SQLException ex) {
                Logger.getLogger(frmSACH.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (tl.size() > 0) {
                JOptionPane.showMessageDialog(this, "Tên loại sách đã tồn tại");
                return false;
            }
        }
        return true;
    }

    private void timkiemLoaisach() {
        String sql = "";
        if (ckbMALS.isSelected()) {
            sql = " Where matl like'" + txtMALS.getText() + "'";
        } else if (ckbTENLS.isSelected()) {
            sql = " Where tentl like N'%" + txtTENLS.getText() + "%'";
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn thuộc tính tìm kiếm");
            return;
        }
        laydulieuLoaisach(sql);
    }
}
